### ISSUE TITLE
你好，请问能写个文档或 demo 演示下怎么在 React 或 vue 中使用吗？

### ISSUE THREAD

**Issue by vortesnail** [mini-peanut/aop-monitor#1]
使用了 README 中的写法，不太行～

**Comment by mini-peanut** [comment]
@vortesnail 把demo push上去了，你看看行不

**Comment by vortesnail** [comment]
@mini-peanut 相当好用啊～
不过还有一个小问题：比如每个 React 组件都需要一份独立的 watchList 吗？相当于重写一遍我想监听到的方法（比如点击，生命周期函数等），那这样的确是和业务解耦了，除掉这个是不是和 代码埋点 没啥差别了呢？

谢谢作者的付出～谢谢🙏

**Comment by mini-peanut** [comment]
> 除掉这个是不是和 代码埋点 没啥差别了呢？
 
@vortesnail 这个没太懂，除掉watchList就相当于没有埋点了呀
业务组件如果不需要埋点就不需要watchList了

**Comment by vortesnail** [comment]
> > 除掉这个是不是和 代码埋点 没啥差别了呢？
> 
> 这个没太懂，除掉watchList就相当于没有埋点了呀

我说的“除掉”是指除了这个”埋点代码与业务代码解耦“的功能。

在watchList里的方法无法得到原来的这个方法某个地方的变量对吗？

比如：
App.js
```js
handleClickA() {
  let a = 3;
}
```

watchList.js
```js
handleClickA() {
  // 在这里我得不到 a？
}
```

**Comment by mini-peanut** [comment]
@vortesnail 得不到，相同的地方在于环境上下文以及入参，组件内定义的变量，watchList是得不到的，需要再定义一遍。

如果需要提出公共的变量，可以放到state里，react可以通过this.state.xx获取，vue同理

**Comment by vortesnail** [comment]
@mini-peanut 好的，非常感谢作者！！！
