### ISSUE TITLE
怎么样才能支持UV，PV等这类页面数据的收集？

### ISSUE THREAD

**Issue by vortesnail** [mini-peanut/aop-monitor#2]
这类数据如何扩展现有代码逻辑得到呢？

**Comment by mini-peanut** [comment]
@vortesnail componentDidMount里去收集就可以吧

**Comment by mini-peanut** [comment]
如果需要同时发送多个埋点，watchList里返回数组的格式

**Comment by vortesnail** [comment]
目前的代码逻辑不支持埋点发送时机的自定义吧，比如我某个点击函数里有异步请求，我想等到请求返回数据之后（或之前）再去上报埋点数据，还没实现吧？

**Comment by mini-peanut** [comment]
@vortesnail 可以把异步之前或者 之后的处理逻辑提炼出来，单独抽成一个方法
